name = "Starlight"
author = "my-daarlin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91bcf151f830b937d9184795796c4acff7a5b594050c97d146578e792140b8d8"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
