name = "Starlight"
author = "my-daarlin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efe17fdc68b5bfd6e6bea7717938c05571c767edb08dc7a8c0118c2f2f50553c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
