name = "Starlight"
author = "my-daarlin"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fefc0e8cf9805cbbc5adef739031175bf30afdb20d3e71791245d0e42250ebb"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
