name = "Starlight"
author = "my-daarlin"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41df4e16670ff78cbaa2fa0bbec1572cb3f956098fa6b77abede8efab2f24c85"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
