name = "Starlight"
author = "my-daarlin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8e34e9b5ef0f4b808f873bcb6b5fb1096afbcd3e9bf7ab9fd4acf86dc0f4250"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
